alter table departments enable row level security;
alter table employees enable row level security;
alter table tasks enable row level security;
alter table task_comments enable row level security;
alter table daily_logs enable row level security;
alter table approvals enable row level security;
alter table notifications enable row level security;
alter table activity_logs enable row level security;
alter table external_sync_logs enable row level security;

create policy "app read departments" on departments for select to anon, authenticated using (true);
create policy "app read employees" on employees for select to anon, authenticated using (true);
create policy "app read tasks" on tasks for select to anon, authenticated using (true);
create policy "app write tasks" on tasks for insert to anon, authenticated with check (true);
create policy "app update tasks" on tasks for update to anon, authenticated using (true);
create policy "app read comments" on task_comments for select to anon, authenticated using (true);
create policy "app write comments" on task_comments for insert to anon, authenticated with check (true);
create policy "app read logs" on daily_logs for select to anon, authenticated using (true);
create policy "app write logs" on daily_logs for insert to anon, authenticated with check (true);
create policy "app read approvals" on approvals for select to anon, authenticated using (true);
create policy "app write approvals" on approvals for insert to anon, authenticated with check (true);
create policy "app update approvals" on approvals for update to anon, authenticated using (true);
create policy "app read notifications" on notifications for select to anon, authenticated using (true);
create policy "app write notifications" on notifications for insert to anon, authenticated with check (true);
create policy "app update notifications" on notifications for update to anon, authenticated using (true);
create policy "app read activity" on activity_logs for select to anon, authenticated using (true);
create policy "app write activity" on activity_logs for insert to anon, authenticated with check (true);
create policy "app read sync logs" on external_sync_logs for select to anon, authenticated using (true);
create policy "app write sync logs" on external_sync_logs for insert to anon, authenticated with check (true);
