alter table departments enable row level security;
alter table projects enable row level security;
alter table business_kpis enable row level security;
alter table business_alerts enable row level security;
alter table business_actions enable row level security;
alter table business_memory enable row level security;
alter table business_integrations enable row level security;
alter table accounting_accounts enable row level security;
alter table accounting_journal_entries enable row level security;
alter table accounting_journal_lines enable row level security;
alter table accounting_contacts enable row level security;
alter table accounting_invoices enable row level security;
alter table accounting_bank_accounts enable row level security;
alter table accounting_bank_transactions enable row level security;
alter table ceo_office_items enable row level security;
alter table marketing_channels enable row level security;
alter table marketing_campaigns enable row level security;
alter table opportunity_radar_runs enable row level security;
alter table company_strategy enable row level security;
alter table strategies enable row level security;
alter table market_reports enable row level security;
alter table opportunities enable row level security;
alter table decisions enable row level security;
alter table financial_transactions enable row level security;
alter table freelancer_assignments enable row level security;
alter table employees enable row level security;
alter table tasks enable row level security;
alter table task_comments enable row level security;
alter table daily_logs enable row level security;
alter table approvals enable row level security;
alter table notifications enable row level security;
alter table activity_logs enable row level security;
alter table external_sync_logs enable row level security;

create policy "app read departments" on departments for select to anon, authenticated using (true);
drop policy if exists "app read projects" on projects;
drop policy if exists "app write projects" on projects;
drop policy if exists "app read business kpis" on business_kpis;
drop policy if exists "app write business kpis" on business_kpis;
drop policy if exists "app read business alerts" on business_alerts;
drop policy if exists "app write business alerts" on business_alerts;
drop policy if exists "app read business actions" on business_actions;
drop policy if exists "app write business actions" on business_actions;
drop policy if exists "app read business memory" on business_memory;
drop policy if exists "app write business memory" on business_memory;
drop policy if exists "app read business integrations" on business_integrations;
drop policy if exists "app write business integrations" on business_integrations;
drop policy if exists "app read accounting accounts" on accounting_accounts;
drop policy if exists "app write accounting accounts" on accounting_accounts;
drop policy if exists "app read accounting journal entries" on accounting_journal_entries;
drop policy if exists "app write accounting journal entries" on accounting_journal_entries;
drop policy if exists "app read accounting journal lines" on accounting_journal_lines;
drop policy if exists "app write accounting journal lines" on accounting_journal_lines;
drop policy if exists "app read accounting contacts" on accounting_contacts;
drop policy if exists "app write accounting contacts" on accounting_contacts;
drop policy if exists "app read accounting invoices" on accounting_invoices;
drop policy if exists "app write accounting invoices" on accounting_invoices;
drop policy if exists "app read accounting bank accounts" on accounting_bank_accounts;
drop policy if exists "app write accounting bank accounts" on accounting_bank_accounts;
drop policy if exists "app read accounting bank transactions" on accounting_bank_transactions;
drop policy if exists "app write accounting bank transactions" on accounting_bank_transactions;
drop policy if exists "app read ceo office items" on ceo_office_items;
drop policy if exists "app write ceo office items" on ceo_office_items;
drop policy if exists "app update ceo office items" on ceo_office_items;
drop policy if exists "app read marketing channels" on marketing_channels;
drop policy if exists "app write marketing channels" on marketing_channels;
drop policy if exists "app read marketing campaigns" on marketing_campaigns;
drop policy if exists "app write marketing campaigns" on marketing_campaigns;
drop policy if exists "app read opportunity radar runs" on opportunity_radar_runs;
drop policy if exists "app write opportunity radar runs" on opportunity_radar_runs;
drop policy if exists "app read company strategy" on company_strategy;
drop policy if exists "app write company strategy" on company_strategy;
drop policy if exists "app read strategies" on strategies;
drop policy if exists "app write strategies" on strategies;
drop policy if exists "app read market reports" on market_reports;
drop policy if exists "app write market reports" on market_reports;
drop policy if exists "app read opportunities" on opportunities;
drop policy if exists "app write opportunities" on opportunities;
drop policy if exists "app read decisions" on decisions;
drop policy if exists "app write decisions" on decisions;
drop policy if exists "app read financial transactions" on financial_transactions;
drop policy if exists "app write financial transactions" on financial_transactions;
drop policy if exists "app read freelancer assignments" on freelancer_assignments;
drop policy if exists "app write freelancer assignments" on freelancer_assignments;
create policy "app read projects" on projects for select to anon, authenticated using (true);
create policy "app write projects" on projects for insert to anon, authenticated with check (length(name) > 0);
create policy "app read business kpis" on business_kpis for select to anon, authenticated using (true);
create policy "app write business kpis" on business_kpis for insert to anon, authenticated with check (length(name) > 0);
create policy "app read business alerts" on business_alerts for select to anon, authenticated using (true);
create policy "app write business alerts" on business_alerts for insert to anon, authenticated with check (length(title) > 0);
create policy "app read business actions" on business_actions for select to anon, authenticated using (true);
create policy "app write business actions" on business_actions for insert to anon, authenticated with check (length(title) > 0);
create policy "app read business memory" on business_memory for select to anon, authenticated using (true);
create policy "app write business memory" on business_memory for insert to anon, authenticated with check (length(title) > 0);
create policy "app read business integrations" on business_integrations for select to anon, authenticated using (true);
create policy "app write business integrations" on business_integrations for insert to anon, authenticated with check (length(id) > 0);
create policy "app read accounting accounts" on accounting_accounts for select to anon, authenticated using (true);
create policy "app write accounting accounts" on accounting_accounts for insert to anon, authenticated with check (length(code) > 0);
create policy "app read accounting journal entries" on accounting_journal_entries for select to anon, authenticated using (true);
create policy "app write accounting journal entries" on accounting_journal_entries for insert to anon, authenticated with check (true);
create policy "app read accounting journal lines" on accounting_journal_lines for select to anon, authenticated using (true);
create policy "app write accounting journal lines" on accounting_journal_lines for insert to anon, authenticated with check (debit >= 0 and credit >= 0);
create policy "app read accounting contacts" on accounting_contacts for select to anon, authenticated using (true);
create policy "app write accounting contacts" on accounting_contacts for insert to anon, authenticated with check (length(name) > 0);
create policy "app read accounting invoices" on accounting_invoices for select to anon, authenticated using (true);
create policy "app write accounting invoices" on accounting_invoices for insert to anon, authenticated with check (total >= 0);
create policy "app read accounting bank accounts" on accounting_bank_accounts for select to anon, authenticated using (true);
create policy "app write accounting bank accounts" on accounting_bank_accounts for insert to anon, authenticated with check (length(name) > 0);
create policy "app read accounting bank transactions" on accounting_bank_transactions for select to anon, authenticated using (true);
create policy "app write accounting bank transactions" on accounting_bank_transactions for insert to anon, authenticated with check (length(description) > 0);
create policy "app read ceo office items" on ceo_office_items for select to anon, authenticated using (true);
create policy "app write ceo office items" on ceo_office_items for insert to anon, authenticated with check (length(title) > 0);
create policy "app update ceo office items" on ceo_office_items for update to anon, authenticated using (true) with check (length(title) > 0);
create policy "app read marketing channels" on marketing_channels for select to anon, authenticated using (true);
create policy "app write marketing channels" on marketing_channels for insert to anon, authenticated with check (length(name) > 0);
create policy "app read marketing campaigns" on marketing_campaigns for select to anon, authenticated using (true);
create policy "app write marketing campaigns" on marketing_campaigns for insert to anon, authenticated with check (length(name) > 0);
create policy "app read opportunity radar runs" on opportunity_radar_runs for select to anon, authenticated using (true);
create policy "app write opportunity radar runs" on opportunity_radar_runs for insert to anon, authenticated with check (length(signal_summary) > 0);
create policy "app read company strategy" on company_strategy for select to anon, authenticated using (true);
create policy "app write company strategy" on company_strategy for insert to anon, authenticated with check (length(id) > 0);
create policy "app read strategies" on strategies for select to anon, authenticated using (true);
create policy "app write strategies" on strategies for insert to anon, authenticated with check (length(name) > 0);
create policy "app read market reports" on market_reports for select to anon, authenticated using (true);
create policy "app write market reports" on market_reports for insert to anon, authenticated with check (length(market_name) > 0);
create policy "app read opportunities" on opportunities for select to anon, authenticated using (true);
create policy "app write opportunities" on opportunities for insert to anon, authenticated with check (length(title) > 0);
create policy "app read decisions" on decisions for select to anon, authenticated using (true);
create policy "app write decisions" on decisions for insert to anon, authenticated with check (length(recommendation) > 0);
create policy "app read financial transactions" on financial_transactions for select to anon, authenticated using (true);
create policy "app write financial transactions" on financial_transactions for insert to anon, authenticated with check (amount >= 0 and length(description) > 0);
create policy "app read freelancer assignments" on freelancer_assignments for select to anon, authenticated using (true);
create policy "app write freelancer assignments" on freelancer_assignments for insert to anon, authenticated with check (length(role_needed) > 0);
create policy "app read employees" on employees for select to anon, authenticated using (true);
create policy "app read tasks" on tasks for select to anon, authenticated using (true);
create policy "app write tasks" on tasks for insert to anon, authenticated with check (true);
create policy "app update tasks" on tasks for update to anon, authenticated using (true);
create policy "app read comments" on task_comments for select to anon, authenticated using (true);
create policy "app write comments" on task_comments for insert to anon, authenticated with check (true);
create policy "app read logs" on daily_logs for select to anon, authenticated using (true);
create policy "app write logs" on daily_logs for insert to anon, authenticated with check (true);
create policy "app read approvals" on approvals for select to anon, authenticated using (true);
create policy "app write approvals" on approvals for insert to anon, authenticated with check (true);
create policy "app update approvals" on approvals for update to anon, authenticated using (true);
create policy "app read notifications" on notifications for select to anon, authenticated using (true);
create policy "app write notifications" on notifications for insert to anon, authenticated with check (true);
create policy "app update notifications" on notifications for update to anon, authenticated using (true);
create policy "app read activity" on activity_logs for select to anon, authenticated using (true);
create policy "app write activity" on activity_logs for insert to anon, authenticated with check (true);
create policy "app read sync logs" on external_sync_logs for select to anon, authenticated using (true);
create policy "app write sync logs" on external_sync_logs for insert to anon, authenticated with check (true);

grant select, insert on projects to anon, authenticated, service_role;
grant select, insert, update on tasks to anon, authenticated, service_role;
grant select, insert, update on approvals to anon, authenticated, service_role;
grant select, insert, update on business_kpis to anon, authenticated, service_role;
grant select, insert, update on business_alerts to anon, authenticated, service_role;
grant select, insert, update on business_actions to anon, authenticated, service_role;
grant select, insert on business_memory to anon, authenticated, service_role;
grant select, insert, update on business_integrations to anon, authenticated, service_role;
grant select, insert, update on accounting_accounts to anon, authenticated, service_role;
grant select, insert, update on accounting_journal_entries to anon, authenticated, service_role;
grant select, insert, update on accounting_journal_lines to anon, authenticated, service_role;
grant select, insert, update on accounting_contacts to anon, authenticated, service_role;
grant select, insert, update on accounting_invoices to anon, authenticated, service_role;
grant select, insert, update on accounting_bank_accounts to anon, authenticated, service_role;
grant select, insert, update on accounting_bank_transactions to anon, authenticated, service_role;
grant select, insert, update on ceo_office_items to anon, authenticated, service_role;
grant select, insert, update on marketing_channels to anon, authenticated, service_role;
grant select, insert, update on marketing_campaigns to anon, authenticated, service_role;
grant select, insert, update on opportunity_radar_runs to anon, authenticated, service_role;
grant select, insert, update on company_strategy to anon, authenticated, service_role;
grant select, insert on strategies to anon, authenticated, service_role;
grant select, insert on market_reports to anon, authenticated, service_role;
grant select, insert on opportunities to anon, authenticated, service_role;
grant select, insert on decisions to anon, authenticated, service_role;
grant select, insert on financial_transactions to anon, authenticated, service_role;
grant select, insert on freelancer_assignments to anon, authenticated, service_role;

alter table governance_roles enable row level security;
alter table approval_policies enable row level security;
alter table decision_audit_log enable row level security;
alter table cost_centers enable row level security;
alter table accounting_period_closes enable row level security;
alter table cash_flow_forecasts enable row level security;
alter table executive_calendar_events enable row level security;
alter table executive_meeting_minutes enable row level security;
alter table executive_daily_briefs enable row level security;
alter table marketing_products enable row level security;
alter table marketing_segments enable row level security;
alter table marketing_offers enable row level security;
alter table marketing_ab_tests enable row level security;
alter table marketing_content_calendar enable row level security;
alter table marketing_funnel_events enable row level security;
alter table opportunity_scores enable row level security;

drop policy if exists "app read governance roles" on governance_roles;
drop policy if exists "app write governance roles" on governance_roles;
drop policy if exists "app read approval policies" on approval_policies;
drop policy if exists "app write approval policies" on approval_policies;
drop policy if exists "app read decision audit log" on decision_audit_log;
drop policy if exists "app write decision audit log" on decision_audit_log;
drop policy if exists "app read cost centers" on cost_centers;
drop policy if exists "app write cost centers" on cost_centers;
drop policy if exists "app read accounting period closes" on accounting_period_closes;
drop policy if exists "app write accounting period closes" on accounting_period_closes;
drop policy if exists "app read cash flow forecasts" on cash_flow_forecasts;
drop policy if exists "app write cash flow forecasts" on cash_flow_forecasts;
drop policy if exists "app read executive calendar events" on executive_calendar_events;
drop policy if exists "app write executive calendar events" on executive_calendar_events;
drop policy if exists "app read executive meeting minutes" on executive_meeting_minutes;
drop policy if exists "app write executive meeting minutes" on executive_meeting_minutes;
drop policy if exists "app read executive daily briefs" on executive_daily_briefs;
drop policy if exists "app write executive daily briefs" on executive_daily_briefs;
drop policy if exists "app read marketing products" on marketing_products;
drop policy if exists "app write marketing products" on marketing_products;
drop policy if exists "app read marketing segments" on marketing_segments;
drop policy if exists "app write marketing segments" on marketing_segments;
drop policy if exists "app read marketing offers" on marketing_offers;
drop policy if exists "app write marketing offers" on marketing_offers;
drop policy if exists "app read marketing ab tests" on marketing_ab_tests;
drop policy if exists "app write marketing ab tests" on marketing_ab_tests;
drop policy if exists "app read marketing content calendar" on marketing_content_calendar;
drop policy if exists "app write marketing content calendar" on marketing_content_calendar;
drop policy if exists "app read marketing funnel events" on marketing_funnel_events;
drop policy if exists "app write marketing funnel events" on marketing_funnel_events;
drop policy if exists "app read opportunity scores" on opportunity_scores;
drop policy if exists "app write opportunity scores" on opportunity_scores;

create policy "app read governance roles" on governance_roles for select to anon, authenticated using (true);
create policy "app write governance roles" on governance_roles for insert to anon, authenticated with check (length(id) > 0);
create policy "app read approval policies" on approval_policies for select to anon, authenticated using (true);
create policy "app write approval policies" on approval_policies for insert to anon, authenticated with check (length(id) > 0);
create policy "app read decision audit log" on decision_audit_log for select to anon, authenticated using (true);
create policy "app write decision audit log" on decision_audit_log for insert to anon, authenticated with check (length(action) > 0);
create policy "app read cost centers" on cost_centers for select to anon, authenticated using (true);
create policy "app write cost centers" on cost_centers for insert to anon, authenticated with check (length(name) > 0);
create policy "app read accounting period closes" on accounting_period_closes for select to anon, authenticated using (true);
create policy "app write accounting period closes" on accounting_period_closes for insert to anon, authenticated with check (length(period) > 0);
create policy "app read cash flow forecasts" on cash_flow_forecasts for select to anon, authenticated using (true);
create policy "app write cash flow forecasts" on cash_flow_forecasts for insert to anon, authenticated with check (true);
create policy "app read executive calendar events" on executive_calendar_events for select to anon, authenticated using (true);
create policy "app write executive calendar events" on executive_calendar_events for insert to anon, authenticated with check (length(title) > 0);
create policy "app read executive meeting minutes" on executive_meeting_minutes for select to anon, authenticated using (true);
create policy "app write executive meeting minutes" on executive_meeting_minutes for insert to anon, authenticated with check (length(title) > 0);
create policy "app read executive daily briefs" on executive_daily_briefs for select to anon, authenticated using (true);
create policy "app write executive daily briefs" on executive_daily_briefs for insert to anon, authenticated with check (length(summary) > 0);
create policy "app read marketing products" on marketing_products for select to anon, authenticated using (true);
create policy "app write marketing products" on marketing_products for insert to anon, authenticated with check (length(name) > 0);
create policy "app read marketing segments" on marketing_segments for select to anon, authenticated using (true);
create policy "app write marketing segments" on marketing_segments for insert to anon, authenticated with check (length(name) > 0);
create policy "app read marketing offers" on marketing_offers for select to anon, authenticated using (true);
create policy "app write marketing offers" on marketing_offers for insert to anon, authenticated with check (length(name) > 0);
create policy "app read marketing ab tests" on marketing_ab_tests for select to anon, authenticated using (true);
create policy "app write marketing ab tests" on marketing_ab_tests for insert to anon, authenticated with check (length(name) > 0);
create policy "app read marketing content calendar" on marketing_content_calendar for select to anon, authenticated using (true);
create policy "app write marketing content calendar" on marketing_content_calendar for insert to anon, authenticated with check (length(topic) > 0);
create policy "app read marketing funnel events" on marketing_funnel_events for select to anon, authenticated using (true);
create policy "app write marketing funnel events" on marketing_funnel_events for insert to anon, authenticated with check (length(stage) > 0);
create policy "app read opportunity scores" on opportunity_scores for select to anon, authenticated using (true);
create policy "app write opportunity scores" on opportunity_scores for insert to anon, authenticated with check (length(opportunity_title) > 0);

grant select, insert, update on governance_roles to anon, authenticated, service_role;
grant select, insert, update on approval_policies to anon, authenticated, service_role;
grant select, insert on decision_audit_log to anon, authenticated, service_role;
grant select, insert, update on cost_centers to anon, authenticated, service_role;
grant select, insert, update on accounting_period_closes to anon, authenticated, service_role;
grant select, insert, update on cash_flow_forecasts to anon, authenticated, service_role;
grant select, insert, update on executive_calendar_events to anon, authenticated, service_role;
grant select, insert, update on executive_meeting_minutes to anon, authenticated, service_role;
grant select, insert, update on executive_daily_briefs to anon, authenticated, service_role;
grant select, insert, update on marketing_products to anon, authenticated, service_role;
grant select, insert, update on marketing_segments to anon, authenticated, service_role;
grant select, insert, update on marketing_offers to anon, authenticated, service_role;
grant select, insert, update on marketing_ab_tests to anon, authenticated, service_role;
grant select, insert, update on marketing_content_calendar to anon, authenticated, service_role;
grant select, insert, update on marketing_funnel_events to anon, authenticated, service_role;
grant select, insert, update on opportunity_scores to anon, authenticated, service_role;
