alter table departments enable row level security;
alter table projects enable row level security;
alter table business_kpis enable row level security;
alter table business_alerts enable row level security;
alter table business_actions enable row level security;
alter table business_memory enable row level security;
alter table business_integrations enable row level security;
alter table employees enable row level security;
alter table tasks enable row level security;
alter table task_comments enable row level security;
alter table daily_logs enable row level security;
alter table approvals enable row level security;
alter table notifications enable row level security;
alter table activity_logs enable row level security;
alter table external_sync_logs enable row level security;

create policy "app read departments" on departments for select to anon, authenticated using (true);
drop policy if exists "app read projects" on projects;
drop policy if exists "app write projects" on projects;
drop policy if exists "app read business kpis" on business_kpis;
drop policy if exists "app write business kpis" on business_kpis;
drop policy if exists "app read business alerts" on business_alerts;
drop policy if exists "app write business alerts" on business_alerts;
drop policy if exists "app read business actions" on business_actions;
drop policy if exists "app write business actions" on business_actions;
drop policy if exists "app read business memory" on business_memory;
drop policy if exists "app write business memory" on business_memory;
drop policy if exists "app read business integrations" on business_integrations;
drop policy if exists "app write business integrations" on business_integrations;
create policy "app read projects" on projects for select to anon, authenticated using (true);
create policy "app write projects" on projects for insert to anon, authenticated with check (length(name) > 0);
create policy "app read business kpis" on business_kpis for select to anon, authenticated using (true);
create policy "app write business kpis" on business_kpis for insert to anon, authenticated with check (length(name) > 0);
create policy "app read business alerts" on business_alerts for select to anon, authenticated using (true);
create policy "app write business alerts" on business_alerts for insert to anon, authenticated with check (length(title) > 0);
create policy "app read business actions" on business_actions for select to anon, authenticated using (true);
create policy "app write business actions" on business_actions for insert to anon, authenticated with check (length(title) > 0);
create policy "app read business memory" on business_memory for select to anon, authenticated using (true);
create policy "app write business memory" on business_memory for insert to anon, authenticated with check (length(title) > 0);
create policy "app read business integrations" on business_integrations for select to anon, authenticated using (true);
create policy "app write business integrations" on business_integrations for insert to anon, authenticated with check (length(id) > 0);
create policy "app read employees" on employees for select to anon, authenticated using (true);
create policy "app read tasks" on tasks for select to anon, authenticated using (true);
create policy "app write tasks" on tasks for insert to anon, authenticated with check (true);
create policy "app update tasks" on tasks for update to anon, authenticated using (true);
create policy "app read comments" on task_comments for select to anon, authenticated using (true);
create policy "app write comments" on task_comments for insert to anon, authenticated with check (true);
create policy "app read logs" on daily_logs for select to anon, authenticated using (true);
create policy "app write logs" on daily_logs for insert to anon, authenticated with check (true);
create policy "app read approvals" on approvals for select to anon, authenticated using (true);
create policy "app write approvals" on approvals for insert to anon, authenticated with check (true);
create policy "app update approvals" on approvals for update to anon, authenticated using (true);
create policy "app read notifications" on notifications for select to anon, authenticated using (true);
create policy "app write notifications" on notifications for insert to anon, authenticated with check (true);
create policy "app update notifications" on notifications for update to anon, authenticated using (true);
create policy "app read activity" on activity_logs for select to anon, authenticated using (true);
create policy "app write activity" on activity_logs for insert to anon, authenticated with check (true);
create policy "app read sync logs" on external_sync_logs for select to anon, authenticated using (true);
create policy "app write sync logs" on external_sync_logs for insert to anon, authenticated with check (true);

grant select, insert on projects to anon, authenticated, service_role;
grant select, insert, update on tasks to anon, authenticated, service_role;
grant select, insert, update on approvals to anon, authenticated, service_role;
grant select, insert, update on business_kpis to anon, authenticated, service_role;
grant select, insert, update on business_alerts to anon, authenticated, service_role;
grant select, insert, update on business_actions to anon, authenticated, service_role;
grant select, insert on business_memory to anon, authenticated, service_role;
grant select, insert, update on business_integrations to anon, authenticated, service_role;
